# embed_fonts.cmake — build-time generator for the UI fonts.
# Run via `cmake -DFONT_DIR=.. -DOUT=.. -P embed_fonts.cmake`.
#
# Turns every assets/fonts/*.ttf into a byte array in one generated header, so the
# modern UI skin loads its type from memory on every target (native, AppImage, web)
# with no runtime asset path. Symbol = k_font_<stem with '-' -> '_'>, plus a
# matching k_font_<stem>_size. The TTFs on disk stay the single source of truth.

file(GLOB _ttfs "${FONT_DIR}/*.ttf")
list(SORT _ttfs)

set(_body "")
foreach(f ${_ttfs})
    get_filename_component(stem "${f}" NAME_WE)
    string(REPLACE "-" "_" sym "${stem}")
    file(READ "${f}" hex HEX)
    string(LENGTH "${hex}" hex_len)
    math(EXPR n "${hex_len} / 2")
    # 0xAB, per byte; break lines every 32 bytes so the header stays diffable/greppable.
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n" bytes "${bytes}")
    string(APPEND _body "alignas(4) inline const unsigned char k_font_${sym}[${n}] = {\n${bytes}\n};\n")
    string(APPEND _body "inline constexpr int k_font_${sym}_size = ${n};\n\n")
endforeach()

set(_header "// GENERATED by cmake/embed_fonts.cmake — DO NOT EDIT.
// Embeds assets/fonts/*.ttf (IBM Plex, SIL OFL 1.1 — see assets/fonts/OFL.txt).
#pragma once

${_body}")

# Only touch the output when it changed, so an unrelated reconfigure doesn't
# recompile everything that includes it.
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
    if(_old STREQUAL _header)
        return()
    endif()
endif()
file(WRITE "${OUT}" "${_header}")
