# embed_shaders.cmake — build-time generator for the compute-kernel shader sources.
# Run via `cmake -DGLSL_DIR=.. -DWGSL_DIR=.. -DOUT=.. -P embed_shaders.cmake`.
#
# Reads every shaders/glsl/*.comp and shaders/wgsl/*.wgsl, pairs them by file stem,
# and emits a generated header exposing:
#     gpu::ShaderSources gpu::embedded_shader(const char* name)
# returning {wgsl, glsl} for the kernel `name` (== file stem), with whichever sides
# exist (a stem may have only a .wgsl or only a .comp during the staged port). The
# dual-backend gpu:: seam compiles the matching side; the canonical .comp/.wgsl on
# disk stay the single source of truth (no inline copy to drift). See webgpu-port-plan.md.

cmake_policy(SET CMP0057 NEW)   # enable the IN_LIST if() operator in -P script mode

file(GLOB _glsl_files "${GLSL_DIR}/*.comp")
file(GLOB _wgsl_files "${WGSL_DIR}/*.wgsl")

set(_defs "")    # symbol definitions
set(_branches "")# accessor if-branches
set(_glsl_stems "")
set(_wgsl_stems "")
set(_all_stems "")

foreach(f ${_glsl_files})
    get_filename_component(stem "${f}" NAME_WE)
    file(READ "${f}" content)
    string(APPEND _defs "inline const char* const k_${stem}_glsl = R\"CHISELSHADER(\n${content})CHISELSHADER\";\n")
    list(APPEND _glsl_stems "${stem}")
    list(APPEND _all_stems "${stem}")
endforeach()

foreach(f ${_wgsl_files})
    get_filename_component(stem "${f}" NAME_WE)
    file(READ "${f}" content)
    string(APPEND _defs "inline const char* const k_${stem}_wgsl = R\"CHISELSHADER(\n${content})CHISELSHADER\";\n")
    list(APPEND _wgsl_stems "${stem}")
    list(APPEND _all_stems "${stem}")
endforeach()

list(REMOVE_DUPLICATES _all_stems)
list(SORT _all_stems)

foreach(stem ${_all_stems})
    set(_w "nullptr")
    set(_g "nullptr")
    if(stem IN_LIST _wgsl_stems)
        set(_w "k_${stem}_wgsl")
    endif()
    if(stem IN_LIST _glsl_stems)
        set(_g "k_${stem}_glsl")
    endif()
    string(APPEND _branches "    if (std::strcmp(name, \"${stem}\") == 0) return ShaderSources{ ${_w}, ${_g} };\n")
endforeach()

set(_header "// GENERATED by cmake/embed_shaders.cmake — DO NOT EDIT.
// Embeds the canonical compute kernels from shaders/{glsl,wgsl}/ as string literals.
#pragma once
#include <cstring>
#include \"gpu/gpu.h\"

namespace gpu {

${_defs}
// Look up an embedded kernel by file stem (e.g. \"mask_paint\"). Returns {wgsl, glsl}
// with whichever sides exist; an unknown name yields {nullptr, nullptr}.
inline ShaderSources embedded_shader(const char* name) {
${_branches}    return ShaderSources{ nullptr, nullptr };
}

} // namespace gpu
")

file(WRITE "${OUT}" "${_header}")
